1. Write a function so that the columns of the output matrix are powers of the input
vector.
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [4]:
import numpy as np


a = np.array ([1,2,4,6])
Y = 4
print(np.vander(a, Y), "\n\n")
print(np.vander(a, Y, increasing=True))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 64  16   4   1]
 [216  36   6   1]] 


[[  1   1   1   1]
 [  1   2   4   8]
 [  1   4  16  64]
 [  1   6  36 216]]


2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
    the given sequence is defined as follows:
    The moving average sequence has n-k+1 elements as shown below.
    The moving averages with k=4 of a ten-value sequence (n=10) is shown below


        i 1 2 3 4 5 6 7 8 9 10
        ===== == == == == == == == == == ==
        Input 10 20 30 40 50 60 70 80 90 100
        y1 25 = (10+20+30+40)/4
        y2 35 = (20+30+40+50)/4
        y3 45 = (30+40+50+60)/4
        y4 55 = (40+50+60+70)/4
        y5 65 = (50+60+70+80)/4
        y6 75 = (60+70+80+90)/4
        y7 85 = (70+80+90+100)/4
    Thus, the moving average sequence has n-k+1=10-4+1=7 values.
    

    Question: Write a function to find moving average in an array over a window:
    Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.


In [14]:
#2 solution

arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window = 3
moving_avg_list = []
for start_idx in range(0, len(arr)):
    end_idx = start_idx + window
    
    if end_idx > len(arr):
        break
    
    window_arr = np.take(arr, range(start_idx, end_idx))
    
    avg = np.average(window_arr)
    print("y"+str(start_idx+1)+":", window_arr, "=>", avg )
    
    
    moving_avg_list.append(avg)
    
print("final list of moving avg:", moving_avg_list)
print("\nThus, the moving average sequence has n-k+1=", len(arr)-window+1 , "values")

y1: [3 5 7] => 5.0
y2: [5 7 2] => 4.666666666666667
y3: [7 2 8] => 5.666666666666667
y4: [ 2  8 10] => 6.666666666666667
y5: [ 8 10 11] => 9.666666666666666
y6: [10 11 65] => 28.666666666666668
y7: [11 65 72] => 49.333333333333336
y8: [65 72 81] => 72.66666666666667
y9: [72 81 99] => 84.0
y10: [ 81  99 100] => 93.33333333333333
y11: [ 99 100 150] => 116.33333333333333
final list of moving avg: [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]

Thus, the moving average sequence has n-k+1= 11 values
